### PR TITLE
split off r-harp output and move to harp 1.16

### PR DESCRIPTION
**Pull request by srepmub**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by srepmub** [comment]
what a horrible experience again. can't find shorter ways of doing this.

**Comment by svniemeijer** [comment]
I've added component definitions to the HARP CMakeLists.txt file.
We can now separate the installations for core, python, and r:

cmake --install . --component core
cmake --install . --component python
cmake --install . --component r

We either have to wait for a next HARP release to implement this, or we include a patch that matches the CMakeLists.txt change.

**Comment by svniemeijer** [comment]
@conda-forge-admin, please rerender

**Comment by svniemeijer** [comment]
Replaced by #25

**Pull request closed without merging**
